### PR TITLE
Direct Optimization Fixes

### PR DESCRIPTION
**Pull request by ethanhung11**

### CODE REVIEW

**Review by eniohodzic — COMMENTED** [review]
Could you remove any unnecessary functions from the tracker object? Is first_entry still needed when self.array is already initialized. 

Also is self.data the tensor with missing values already added? I guess is self.array tracking the fit error or the imputed error?

**Comment by ethanhung11** [comment]
self.data should be the original data (can have missingness) before imputation

**Review by eniohodzic — COMMENTED** [review]
So when `tracker` is called, the error between `self.data` and `tfac` is computed for each iteration. Where is the imputation error saved then? Unless `self.data` is the tensor containing only values that were removed from the tensor used as input for the method.

**Comment by ethanhung11** [comment]
Tracker doesn't save the `tFac `object itself, it simply compares the current `tFac` (which is a CPTensor object) passed by the method (during each iteration) to the `self.data`. The first line when the object is called calculates the R2X value and saves it in `self.array` (see the dunder call function). If the method you're fixing up doesn't return a CPTensor object to the callback but something else instead it might be easier to work that out in person.

**Pull request merged**
