### PR TITLE
Tracker

### PR DESCRIPTION
**Pull request by eniohodzic**
Make sure it works for direct opt method as well. Let me know of any issues that arise if not.

### CODE REVIEW

**Comment by ethanhung11** [comment]
what's the purpose of `self.impute_array`?

**Comment by ethanhung11** [comment]
what's the difference between `self.array` and `self.impute-array`?

**Comment by eniohodzic** [comment]
`self.array` calculates the error between entries that are 1) conserved between the input tensor after applying artificial missingness and original whole tensor and 2) those same indices in the reconstructed tensor from its factors. 

`self.impute_array` calculates the error between entries that are 1) removed from the original tensor where `self.mask` is set to 0. This is used to create a tensor copy that contains only values that were removed from the original tensor and 2) only the indices of removed entries in the reconstructed tensor from its factors. 

the complement `self.mask` and the input tensor should have an intersection that has no real values.

**Comment by ethanhung11** [comment]
Ah, I see. For `self.array`, I believe function `calcR2X()` calculates it for all values (both conserved values before/after imputation as well the values artificially dropped during imputation). Is that going to be an issue?

**Comment by eniohodzic** [comment]
It should only calculate norm between values that are non-nan in the tensor. However, in the case that missing values are set to something else for a method than it will calculate the error between tfac and the placeholder. I will push a commit to handle that case. 

Can you do a `np.isfinite` to make one after the fact and pass it with the other inputs?

**Review by ethanhung11 — APPROVED** [review]

**Pull request merged**
